### ISSUE TITLE
Code Release Date

### ISSUE THREAD

**Issue by aniskacem** [QhelDIV/ShapeFormer#1]
Dear authors, 
This seems to be a very promising work! Any detailed plan on when to release the source codes? 
Looking forward to playing with this work! 
Many thanks in advance! 
Cheers,

**Comment by QhelDIV** [comment]
Thanks for your interest in ShapeFormer. 
We will release the cleaned code in March soon.

**Comment by amiltonwong** [comment]
Hi, @QhelDIV ,

Any update on the code release?

Thanks~

**Comment by QhelDIV** [comment]
Hi @amiltonwong,
Thanks for your attention.
Currently, my team is working on a project for submission and will start to clean the code after the deadline (March 7).

**Comment by aniskacem** [comment]
Hi, any news about the codes? We are really excited about the release! 

Thanks!

**Comment by Golriz-code** [comment]
Hi,
Any update on the code release?
Thanks

**Comment by QhelDIV** [comment]
Hi,
Thanks for your interest.
We just released the core code with its hyperparameter configurations. 
The data, pretrained model and more stuff are still on the way. 
The complete code will be released before June.
Please stay tuned!

**Comment by QhelDIV** [comment]
Hi all, 
The full code is released.
Please have a try :D.
