### ISSUE TITLE
Hi, i want to ask some question about VQDIF-only

### ISSUE THREAD

**Issue by Frreed** [QhelDIV/ShapeFormer#12]
Hi，very thanks to your amazing work. 

I want to ask what do you mean VQDIF-only. Is that means only use partail point cloud as the VQDIF's input and generate the results ?

I used partial point cloud as the input of VQDIF and generated some results. But it looks sightly different with your paper

![屏幕截图(17)](https://user-images.githubusercontent.com/93081193/220562765-8ee07eae-b882-4eff-b308-fd42ac109302.png)
![屏幕截图(18)](https://user-images.githubusercontent.com/93081193/220562779-e0e40eb4-9bf7-4d67-86a3-ccc0bcbd7e19.png)

**Comment by QhelDIV** [comment]
The VQDIF-Only baseline is used to prove that the generative modeling is essential to have better completions.
It is trained differently compared to VQDIF model.
For VQDIF model, the input is complete point cloud and the supervision signal is complete shapes.
For VQDIF-Only baseline, the input is partial point cloud and the supervision signal is still complete shapes.
This means that VQDIF-Only works similarly as the OccNet or ConvONet baselines -- map the partial shape to complete shape. While the VQDIF model is only trained for reconstruction, not trained for completion, this is why when you give the partial point cloud the result is still partial shapes.

To obtain the VQDIF-Only baseline's result, you just need to retrain the VQDIF model with the input changed to partial shapes. In this way the model will try to hallucinate the missing parts.

Hope this helps!

**Comment by Frreed** [comment]
@QhelDIV Hi, really thank for your reply. I got your point now. thanks, good luck!
