### ISSUE TITLE
ModuleNotFoundError: No module named 'nnrecon'

### ISSUE THREAD

**Issue by w080707** [QhelDIV/ShapeFormer#2]
Hi, 

When I run  'python -m shapeformer.trainer --opts configs/demo/demo_shapeformer.yaml --gpu 0 --mode "run" ', there is an error:
ModuleNotFoundError: No module named 'nnrecon'

I didn't find public library named 'nnrecon', and in your code, it refers to the local path 'sys.path.append('/studio/nnrecon')'.

Do you have any suggestions to solve this problem?

Thanks.

**Comment by QhelDIV** [comment]
Sorry, it turns out the pre-trained model in google drive is not updated, which contains incorrect names.
I will tell you when the latest checkpoints are uploaded.

**Comment by w080707** [comment]
> Sorry, it turns out the pre-trained model in google drive is not updated, which contains incorrect names. I will tell you when the latest checkpoints are uploaded.

Thanks so much.

**Comment by w080707** [comment]
thanks a lot
