### ISSUE TITLE
Error encountered during mesh sampling

### ISSUE THREAD

**Issue by dqj5182** [QhelDIV/ShapeFormer#21]
I got an error "Error encountered during mesh sampling" after running `python -m shapeformer.trainer --opts configs/demo/demo_vqdif.yaml --gpu 0 --mode "run"`

The problem seem to stem from the [code in here](https://github.com/QhelDIV/ShapeFormer/blob/f305e41a6f90f3ed083b75db9c68e80b031d0c0d/xgutils/geoutil.py#L242).

After debugging, it seemed that the number of outputs of "igl.random_points_on_mesh(sampleN, vert, face)" is three, not two.
May I ask how to solve this problem?

**Comment by HochCC** [comment]
+1

**Comment by HochCC** [comment]
> I got an error "Error encountered during mesh sampling" after running `python -m shapeformer.trainer --opts configs/demo/demo_vqdif.yaml --gpu 0 --mode "run"`
> 
> The problem seem to stem from the [code in here](https://github.com/QhelDIV/ShapeFormer/blob/f305e41a6f90f3ed083b75db9c68e80b031d0c0d/xgutils/geoutil.py#L242).
> 
> After debugging, it seemed that the number of outputs of "igl.random_points_on_mesh(sampleN, vert, face)" is three, not two. May I ask how to solve this problem?

 I also meet this error in libigl-2.5.1, sovling it by degrading to libigl-2.4.1
