### ISSUE TITLE
Re-training ShapeFormer on custom dataset

### ISSUE THREAD

**Issue by dqj5182** [QhelDIV/ShapeFormer#22]
If I wish to re-train ShapeFormer on custom dataset, is it okay to skip the training of VQDIF-16 and just directly fine-tune ShapeFormer?

In the training section (Usage) of readme, it seems that the training is conducted in two-stage process: 1) VQDIF-16, 2) ShapeFormer. But I wish to train only once.

Would fine-tuning ShapeFormer directly without VQDIF-16 training process (of course the pre-trained weight provided by this repo will be loaded) affect highly negatively on performance perspective? In short, will skipping the VQDIF-16 training process affect the performance a lot?

**Comment by QhelDIV** [comment]
Yes, you can skip retraining the VQDIF-16. It won't make a huge difference unless your custom data has significantly different geometry features than those in ShapeNet dataset.

**Comment by dqj5182** [comment]
Thanks for your quick reply!
Really appreciate it
