### ISSUE TITLE
'Ytg' in the IMNET2_64 dataset

### ISSUE THREAD

**Issue by oattao** [QhelDIV/ShapeFormer#3]
Thank you very much for your source code. 
I am trying to run it with your pre-processed dataset IMNET2_64. 
Unfortunately I can not understand the component 'Ytg' in hdf5 file.
Could you please briefly explain what it is and how to make that component in the data?

**Comment by QhelDIV** [comment]
Hi, thanks for your question.
Here is a brief description of the variable names:

> `tg` stands for `target`, which is the samples (probes) of the target occupancy fields.
> `bd`, or `boundary` stands for the points sampled from the shape surface.
> `ct` stands for `context`, which is the partial point cloud that we want to complete.
> `X` stands for point coordinate.
> `Y` stands for the occupancy value of the point coordinate.

The `target` and `context` names come from the field of meta-learning.

And more specifically for your question, the `Ytg` in the hdf5 file stands for the occupancy value of the probes `Xtg`.
In the case of `IMNET2_64`, `Xtg` is the collection of the 64-grid coordinates, which has the shape of `(64**3, 3)` and `Ytg` is the corresponding occupancy value.

**Comment by oattao** [comment]
Hi, thank for your reply.
Could you please tell me how to obtain 'Ytg' from any point cloud '? Or which function in your source code used to do that?
