### ISSUE TITLE
data processing of a new mesh from shapenet

### ISSUE THREAD

**Issue by linjing7** [QhelDIV/ShapeFormer#9]
Hi, thanks for your elegant and solid work. I have two questions about the code:
1. I want to perform shape completion with some meshes (e.g., a subset from shapenet, which is not included in IMNet). I wonder whether the data processing of the mesh is the same as DFAUST? That is, can I run `generate_dfaust_sdf_samples.py` to generate the training pair?  If not, could you please provide the data processing code? Thanks a lot!
2. If I want to train the model on DFAUST, except changing the `datamodule_opt` in the yaml file, what else needs I to modify?

**Comment by QhelDIV** [comment]
1. Yes, this generate_dfaust_sdf_samples.py file generate the training data from a mesh.
2. You only need to modify the datamodule_opt configs since the model hyperparameters are the same.

**Comment by linjing7** [comment]
Okay, thanks for your reply!
